language: php

php:
  - '7.3'

services:
  - postgresql

before_script:
  - psql -c "CREATE USER formadyto WITH PASSWORD 'db_password';" -U postgres
  - psql -c "CREATE DATABASE formadyto;" -U postgres
  - psql -c "GRANT ALL PRIVILEGES ON DATABASE formadyto TO formadyto;" -U postgres

env:
    - DATABASE_URL="mysql://formadyto:db_password@127.0.0.1:5432/formadyto"

script:
   - composer install
   - php bin/console doctrine:migrations:migrate -n
   - php bin/console doctrine:fixtures:load -q
   - php bin/phpunit
