language: php

php:
  - '7.3'

services:
  - postgresql

before_script:
  - psql -c "CREATE USER forma WITH PASSWORD 'db_password';" -U postgres
  - psql -c "CREATE DATABASE forma;" -U postgres
  - psql -c "GRANT ALL PRIVILEGES ON DATABASE forma TO forma;" -U postgres

env:
    - DATABASE_URL="pgsql://forma:db_password@127.0.0.1:5432/forma"

script:
   - composer install
   - php bin/console doctrine:migrations:migrate -n
   - php bin/console doctrine:fixtures:load -q
   - php bin/phpunit
